# Default values for eck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 7.2.0
nodes:
  - nodeCount: 1
    config:
      master: true
      data: true
      ingest: true
