pool:
  vmImage: "ubuntu-latest"

variables:
  GO111MODULE: "on"

steps:
  - task: GoTool@0
    inputs:
      version: '1.13.15'

  - task: Go@0
    displayName: 'Get Dependencies'
    inputs:
      command: 'mod'
      arguments: 'download'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Go@0
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '-v ./test/...'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
