pool:
  vmImage: "ubuntu-latest"

variables:
  GO111MODULE: "on"

steps:
  - task: GoTool@0
    displayName: 'Install Go v1.13.15'
    inputs:
      version: '1.13.15' # should match go version in go.mod

  - task: HelmInstaller@1
    displayName: 'Install Helm'
    inputs:
      helmVersionToInstall: '2.14.3' # should match dependency in go.sum

  - task: Go@0
    displayName: 'Get Dependencies'
    inputs:
      command: 'mod'
      arguments: 'download'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: |
      which go
      go version

      which helm
      helm version
    displayName: 'Versions'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: Go@0
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '-v ./test/...'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
