config:
subcomponents:
  portworx:
    namespace: "portworx"
    injectNamespace: true
    config:
      internalKVDB: true
      etcdEndPoint: # Set internal KVDB to false if you wish to use a custom etcdEndpoint
      AKSorEKSInstall: true
      envVars: "API_SERVER=http://lighthouse-new.portworx.com;"
      secretType: "KVDB"

       