name: "prometheus-grafana"
type: static
path: "./manifests"
subcomponents:
  - name: "grafana"
    type: helm
    source: "https://github.com/helm/charts"
    method: "git"
    path: "stable/grafana"
    version: "247a3076790511b21000f4071e41bbf6bf4a8fc4"
  - name: "prometheus"
    type: helm
    source: "https://github.com/helm/charts"
    method: "git"
    path: "stable/prometheus"
